// Generated by https://quicktype.io

export interface ProductsResponse {
  id: number;
  title: string;
  description: string;
  price: string;
  brand: string;
  createdAt: string;
  updatedAt: string;
  categoryId: number;
  images: Image[];
  category: Category;
}

export interface Category {
  id: number;
  name: string;
}

export interface Image {
  id: number;
  url: string;
}
